name: CI/CD

# Controls when the workflow will run
on:
  # Activates the workflow when there is a push to the main branch
  push:
    branches: [main]

  # Allows you to manually execute this pipeline from the Actions tab
  workflow_dispatch:

# A workflow run consists of one or more jobs that can be executed either sequentially or concurrently
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true  # Opt-out of Node.js 20 migration temporarily
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }} 

    steps:
      - uses: actions/checkout@v3  # Compatible with Node.js 16
      - uses: actions/setup-python@v4  # Compatible with Node.js 16
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt  # Install requirements to enable GitHub to run tests
      - run: python chat.py

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: chat-bot-ai-server
          heroku_email: drihmia.redouane@gmail.com

